### ISSUE TITLE
Compatability between tbl_svysummary() and srvyr::as_survey()-generated tbl_svy objects

### ISSUE THREAD

**Issue by clmawhorter** [ddsjoberg/gtsummary#886]
**Problem**
Hello there, I've been trying to use @larmarange's brilliant `tbl_svysummary()` to summarize survey data that is knit via Rmd to an HTML {gtsummary} output. Colleagues of mine have had success using srvyr-generated tbl_svy objects (i.e. `srvyr::as_survey_design()`) with `tbl_svysummary()`, but my luck doesn't seem to be the same. The issue appears to be in how `as_survey_design()` is creating the x$call element, which interferes with `tbl_svysummary()`'s attempts to subset the dataset, ending in the error: `Error: $ operator is invalid for atomic vectors`. 

I described my problem in detail in this stackoverflow post: [https://stackoverflow.com/questions/67369601/error-operator-is-invalid-for-atomic-vectors-when-using-srvyr-and-tbl-svysumm](url). @ddsjoberg replied (very quickly!) to suggest making a Feature request on github, so here I am. 

**Proposed Solution**
Allow compatability between `srvyr::as_survey_design()`-generated tbl_svy objects and `tbl_svysummary()`. I _think_ that a workaround where `tbl_svysummary()` tried to call the tbl_svy subsets directly (i.e. `x$strata` rather than `x$call$strata`) would solve the problem. But I am certainly not possessed of the programming capability to understand how to make that happen, or even to know why suggesting such a fix might be worthless...

**Alternatives Considered**
I have tried to implement the same code using `survey::svydesign()` but the Rmd code I am using is designed for use with {srvyr} so the changes required are quite intricate. We are running a very large dataset (cannot share for privacy reasons), which may be contributing to the complexity.

**Additional context**
One key issue that I highlighted in my stackoverflow post is that other colleagues running the exact same Rmd code I have and have not had any issues. I mention this again because if there is some way that the srvyr-tbl_svysummary() connection already exists, I don't want you all to have to do more work!

**Comment by ddsjoberg** [comment]
Thank you for the post @clmawhorter ! Full disclosure, I don't work with survey data and I am not familiar with the packages, e.g. I don't know why one would use srvyr over survey.

@larmarange would you like to make updates to accept srvyr objects?  If so, we'd also want to make sure the srvyr objects also work with `tbl_uvregression()` and `tbl_strata()`

**Comment by larmarange** [comment]
I will try to have a look into it. A quick comment:

We are looking to `$call` only when `include` is not provided. So it should be a problem somewhere else. I need to investigate `srvyr`, a package I do not use.

**Comment by larmarange** [comment]
OK, this simple commit https://github.com/ddsjoberg/gtsummary/pull/887/commits/64981c3e2b6bedfd882d4071dfb893eebd48a3c3  fix the issue. No error is produced.

However, it is not complete as survey col are not removed in the case of srvyr objects

**Comment by larmarange** [comment]
OK I just updated PR #887 

It should be OK. @clmawhorter could you please do some tests? On my machine, it's now working correctly.

**Comment by clmawhorter** [comment]
Thanks both! Will test asap and get back to you.

**Comment by ddsjoberg** [comment]
@clmawhorter it is working for me.....



``` r
library(gtsummary)

data(api, package = "survey")
strat_design_srvyr <- 
  apistrat %>%
  srvyr::as_survey_design(1, strata = stype, fpc = fpc, weight = pw,
                          variables = c(stype, both, starts_with("api"))) 

strat_design_srvyr %>%
  tbl_svysummary(
    # stratify summary statistics by the "both" column
    by = both, 
    # summarize a subset of the columns
    include = c(api00, api99, both),
    # adding labels to table
    label = list(api00 ~ "API in 2000",
                 api99 ~ "API in 1999")
  ) %>%
  add_p() %>%   # comparing values by "both" column
  add_overall() %>%
  as_kable() # convert to kable to display on github
```

| **Characteristic** | **Overall**, N = 6,194 | **No**, N = 2,236 | **Yes**, N = 3,958 | **p-value** |
|:-------------------|:-----------------------|:------------------|:-------------------|:------------|
| API in 2000        | 667 (562, 755)         | 641 (528, 743)    | 671 (588, 765)     | 0.035       |
| API in 1999        | 631 (525, 727)         | 636 (524, 724)    | 625 (526, 727)     | 0.8         |

<sup>Created on 2021-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by clmawhorter** [comment]
Thanks @ddsjoberg - for some reason I'm still getting the same error. Seems like the issue may be local... apologies...

**Comment by ddsjoberg** [comment]
are you installing the version of gtsummary from the pull request?

**Comment by ddsjoberg** [comment]
@larmarange thank you so much for the added feature!

@clmawhorter i merged the pull request with the master branch.  you can install it with `remotes::install_github("ddsjoberg/gtsummary")`. please do report back and confirm the update works for your case

**Comment by clmawhorter** [comment]
Thanks so much @larmarange @ddsjoberg - just installed with the suggested path and now the update works! Confirmed that it functions correctly with both the example code and with my actual project. Much appreciated!
